_wandb:
    value:
        cli_version: 0.26.1
        e:
            ve48ghk09ej2yksnezae99tbthh1ino4:
                args:
                    - train
                    - full_train
                    - --fold
                    - "3"
                codePath: gbm.py
                codePathLocal: gbm.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "235149799424"
                        used: "27842592768"
                email: fatehi.arash@gmail.com
                executable: /home/afatehi/.penvs/venv-gbm/bin/python
                git:
                    commit: dc1f0db13c7c7821b8e50540abd3503a064b4fe6
                    remote: https://github.com/platonic-realm/gbm-segmentation
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-aaacc4eb-3cb0-b933-68d3-2ccef4f7c7a1
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-36f51e82-3a0b-ef1f-8705-fb5e8805e937
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-c3ea3290-add8-ff57-0a64-2616b3cc9a5e
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-64db4f26-c663-eb65-a28e-e567dbbc736d
                host: lyn-gpu-03
                memory:
                    total: "540793352192"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.39
                program: /home/afatehi/.vix/projects/gbm-seg/gbm.py
                python: CPython 3.9.16
                root: /home/afatehi/.vix/projects/gbm-seg
                slurm:
                    cluster_name: (null)
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000FFFF0000FFFF
                    cpu_bind_list: "0x0000FFFF0000FFFF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    distribution: cyclic
                    gpus_on_node: "4"
                    gtids: "0"
                    job_cpus_per_node: "32"
                    job_end_time: "1778927237"
                    job_gid: "666"
                    job_gpus: 0,1,2,3
                    job_group: uniuser
                    job_id: "41675"
                    job_name: gbm_full_train_f3
                    job_nodelist: lyn-gpu-03
                    job_num_nodes: "1"
                    job_partition: train
                    job_qos: normal
                    job_start_time: "1778754437"
                    job_uid: "396154"
                    job_user: afatehi
                    jobid: "41675"
                    launch_node_ipaddr: 134.95.10.244
                    localid: "0"
                    mem_per_node: "307200"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: lyn-gpu-03
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "-1"
                    procid: "0"
                    pty_port: "37685"
                    pty_win_col: "142"
                    pty_win_row: "36"
                    srun_comm_host: 134.95.10.244
                    srun_comm_port: "35679"
                    step_gpus: 0,1,2,3
                    step_id: "0"
                    step_launcher_port: "35679"
                    step_nodelist: lyn-gpu-01
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/afatehi/.vix/projects/gbm-seg
                    submit_host: lyn-gpu-01
                    task_pid: "89728"
                    tasks_per_node: "1"
                    topology_addr: lyn-gpu-03
                    topology_addr_pattern: node
                    tres_per_task: cpu:32
                startedAt: "2026-05-14T10:27:24.513421Z"
                writerId: ve48ghk09ej2yksnezae99tbthh1ino4
        m: []
        python_version: 3.9.16
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 15
                - 16
            "4": 3.9.16
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
fold:
    value: 3
inference:
    value:
        device: cuda
        inference_ds:
            batch_size: 16
            path: /projects/ag-bozek/afatehi/gbm/experiments/full_train/datasets/ds_test/
            pin_memory: true
            pixel_stride:
                - 1
                - 64
                - 64
            sample_dimension:
                - 12
                - 256
                - 256
            scale_factor: 6
            workers: 8
        interpolate: true
        morph:
            kernel_ave_size: 5
            thickness_clip_max: 1400
        number_class: 2
        post_processing:
            enabled: true
            kernel_size: 3
            min_2d_size: 500
            min_3d_size: 5000
        result_dir: ""
        snapshot_path: ""
        stitching: gaussian
logging:
    value:
        log_file: logs/train.fold_3.log
        log_level: DEBUG
        log_std: true
        log_summary: false
root_path:
    value: /projects/ag-bozek/afatehi/gbm/experiments/full_train/
trainer:
    value:
        compile: true
        cont_alpha: 0.7
        cont_beta: 0.3
        cudnn_benchmark: false
        deep_supervision:
            enabled: false
            levels: 2
        device: cuda
        dp: true
        epochs: 10
        loss: Cont
        loss_weights:
            - 3
            - 7
        metrics:
            - Loss
            - TruePositiveRate
            - PositivePredictiveValue
            - Dice
            - JaccardIndex
        metrics_class_ids:
            - 1
        mixed_precision: true
        model:
            decoder_kernel:
                - 3
                - 3
                - 3
            decoder_padding: same
            encoder_kernel:
                - 3
                - 3
                - 3
            encoder_padding: same
            feature_maps:
                - 64
                - 128
                - 256
                - 512
            name: unet_3d
            swin_unetr:
                attn_drop_rate: 0
                depths:
                    - 2
                    - 2
                    - 2
                    - 2
                drop_rate: 0
                feature_size: 24
                mlp_ratio: 4
                num_heads:
                    - 3
                    - 6
                    - 12
                    - 24
                qkv_bias: true
                window_size_xy: 7
                z_deduction_per_stage: 2
        optim:
            lr: 0.0001
            name: adam
        report_freq: 100
        result_path: ./results-train/
        scheduler:
            mode: max
            name: reduce_on_plateau
        snapshot_path: ./snapshots/fold_3
        train_ds:
            augmentation:
                enabled_offline: false
                enabled_online: true
                methods_offline:
                    - - _zoom
                      - 2
                    - - _zoom
                      - 1.7
                    - - _zoom
                      - 1.3
                    - - _zoom
                      - 0.7
                    - - _zoom
                      - 0.5
                    - - _twist_clock
                      - "0.5"
                    - - _twist_reverse
                      - "0.5"
                    - - _rotate_random
                      - "0.2"
                methods_online:
                    blur: 0.2
                    channel_drop: 0.3
                    crop: 0.2
                    rotate: 0.2
                    scale: 6
                workers: 8
            batch_size: 16
            ignore_stride_mismatch: true
            path: /projects/ag-bozek/afatehi/gbm/experiments/full_train/datasets/ds_train/
            pin_memory: true
            pixel_stride:
                - 1
                - 64
                - 64
            sample_dimension:
                - 12
                - 256
                - 256
            shuffle: true
            workers: 4
        valid_ds:
            batch_size: 16
            ignore_stride_mismatch: true
            path: /projects/ag-bozek/afatehi/gbm/experiments/full_train/datasets/ds_valid/
            pin_memory: true
            pixel_stride:
                - 1
                - 128
                - 128
            sample_dimension:
                - 12
                - 256
                - 256
            shuffle: false
            workers: 8
        visualization:
            chance: 0.3
            enabled: true
            gif: true
            path: ./visuals/fold_3
            tif: false
        wandb:
            enabled: true
            entity: gbm-project
            project: gbm-seg
            run_name: null
        z_scale: 6
